print("========== CATATAN BELANJA ==========")
print("========== Daftar 1 ==========")
print("Daftar Belanja 1: ['Sikat Gigi', 'Odol', 'Shampoo', 'Sabun', 'Ciduk']")
print()
print("==========Daftar 2 ==========")
print("Daftar Belanja 2: ['Teh', 'Gula', 'Garam', 'Micin', 'Kecap']")
print()
print("Jawab dengan angka [1/2]")
print("1. Rubah Belanjaan")
print("2. Keluar")
pilih= int (input("Masukkan pilihan:"))
namaitem1= input("Masukkan nama item ke daftar 1:")
namaitem2= input("Masukkan nama item ke daftar 2:")
index= input("Masukkan index yang ingin dirubah:")
